const seedUser = {
    users: [{
        full_name: "John Doe",
        phone_number: 1234567890,
        email: "john.doe@example.com",
        avatar: "avatar1.jpg",
        password: "password123",
        roles: ["user"],
        isVerified: true,
        isApproved: false,
        otp: "123456",
        verificationToken: "token123",
        verificationTokenExpiry: new Date(),
        resetPasswordToken: "resetToken123",
        resetPasswordExpiry: new Date(),
    },
    {
        full_name: "Jane Smith",
        phone_number: 9876543210,
        email: "jane.smith@example.com",
        avatar: "avatar2.jpg",
        password: "pass123",
        roles: ["seller"],
        isVerified: true,
        isApproved: true,
        otp: "654321",
        verificationToken: "token456",
        verificationTokenExpiry: new Date(),
        resetPasswordToken: "resetToken456",
        resetPasswordExpiry: new Date(),
        NID: 987654321,
        address: "456 Park Ave, Town",
        bank_account: 123456789,
        earnings: 5000,
    },
    {
        full_name: "Admin User",
        email: "admin@gmail.com",
        avatar: "avatar3.jpg",
        password: "admin123",
        roles: ["admin"],
        isVerified: true,
        isApproved: true,
        otp: "987654",
        verificationToken: "token789",
        verificationTokenExpiry: new Date(),
        resetPasswordToken: "resetToken789",
        resetPasswordExpiry: new Date(),
    }],
};

module.exports = seedUser;
